#ifndef HMAC_CPP_VERSION_HPP
#define HMAC_CPP_VERSION_HPP

#define HMAC_CPP_VERSION_MAJOR 0
#define HMAC_CPP_VERSION_MINOR 4
#define HMAC_CPP_VERSION_PATCH 0
#define HMAC_CPP_VERSION "0.4.0"

#endif // HMAC_CPP_VERSION_HPP
