name: CI-Linux

on:
  push:
    branches:
      - main
      - release/**
      - stable
  pull_request:
    branches:
      - main
      - release/**
      - codex/**

jobs:
  Tests-Linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        std: [11, 17]
    steps:
      - uses: actions/checkout@v3
      - name: Build and Run Tests
        run: |
          sudo apt-get update && sudo apt-get install -y cmake
          CXX_STANDARD=${{ matrix.std }} ./scripts/run_tests.sh
