name: Tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Run Tests
        run: |
          sudo apt-get update && sudo apt-get install -y cmake
          ./scripts/run_tests.sh
